### ISSUE TITLE
Performance degradation of the LAN

### ISSUE THREAD

**Issue by lgbm** [alandau/arpspoof#10]
Hello!

After some time running, the performance degradation of the local network is getting worse along the time. Is a issue?

**Comment by alandau** [comment]
What exactly do you mean by performance degradation? How do you see and measure it?

While I'm not aware of any perf issues, this is a tool for learning and not necessarily prod-ready, so they may exist.

**Comment by lgbm** [comment]
So, If I trying spoofing 192.168.1.3 victm, along the time 192.168.1.3 is getting more more latency (like under congestion).. reaching a general network failure.

I Just asking, If this issues are spoofing techniques side effects or software performance.

**Comment by alandau** [comment]
Getting higher latency is totally anticipated, since the victim's traffic is not routed through the local machine (the one you run arpspoof on), and this routing is done on a single core in a totally unoptimized way. I don't know why this leads to a "general network failure" (whatever that is).

Being high-performant was not one of the goals of this project, but if you want to optimize it, feel free to send a pull request.
