### ISSUE TITLE
Arpspoof gives 2nd pc no internet error

### ISSUE THREAD

**Issue by pubgrad** [alandau/arpspoof#4]
I get no internet on victim(2nd) pc if I arpspoof that computer ipv4. Any fix please? Also it says redirecting to 192.168.1.1 which is not my pc ip from where I am running arpspoof

**Comment by alandau** [comment]
If 192.168.1.1 is your router/gateway, then the message is correct.

As for why you have no Internet, there might be tons of reasons. Can you capture a .pcap on the victim computer as well as on the arpspoof-running computer while trying to open a few websites? This might shed some light.

**Comment by pubgrad** [comment]
I also modifed ipenabler from 0 to 1 in regedit and enabled ip forwarding via powershell.

How do I capture .pcap? Tell me step by step I will and then give you .pcap file

Do I need wireshark too or winpcap is enough?

**Comment by alandau** [comment]
You don't need IP forwarding with arpspoof, as arpspoof does that internally. It could be that this is the problem.

You need Wireshark since WinPcap is just a library. Capture packets then save into a file. There are lots of Wireshark tutorials around, but it should be pretty easy to find the right toolbar buttons etc. even without.

Can you explain what are you trying to do with arpspoof? Most uses I can imagine require Wireshark to look at the diverted packets. If this is not your goal, perhaps arpspoof is the wrong tool.

**Comment by pubgrad** [comment]
Do I need to use ethernet on both pc? Pc running arpspoof has wifi.

I used to connect pc B to pc A via windows builtin vpn. A program then reads the packets from pc B on pc A. Vpn no longer working so I wanted to try arpspoof.

Someone told me just download arpspoof and enter ip address of pc B in cmd and it will work but instead of transferring or replicating packets it ddos pc B.

I am using for the same purpose as simonmy who has opened another issue

**Comment by alandau** [comment]
WiFi should work as well as Ethernet.

Simonmy's issue (#5) was fixed by uninstalling WinPcap and installing Wireshark (which contains a copy of WinPcap). You can try this too.

**Comment by alandau** [comment]
Please reopen if you still have issues
