### ISSUE TITLE
Can't resolve victim IP, is it up? (after 1 day of spoof testing)

### ISSUE THREAD

**Issue by 07c0ff3a590b** [alandau/arpspoof#9]
Yesterday I've came across this tool for a quick ARP spoof test.

Have used it for a couple of hours on the same laptop and network without any issues.
But today as I tried to run it again, I'm getting this error:
![image](https://user-images.githubusercontent.com/55628546/65374980-325f0480-dc90-11e9-944f-ee98660008fd.png)

You can see the AIPS scanned these clients without a problem using WinPcap (or nPcap in compatbile WinPcap mode) while on the other hand **arpspoof** gives out the error **Can't resolve victim IP, is it up?**.

I tried installing nPcap without WinPcap compatible mode, vice versa and nPcap only or WinPcap only. Nothing worked.

But the other freeware applications like SmartSniff (smsniff) and Advanced IP Scanner (aips) still work.

Edit 1: 192.168.0.8 is my phone. So I'm definitely sure It's on the network! Also no NAT or firewalls are set up because no router options we're tampered with. Everything is the same as it was yesterday (during the tests)

**Comment by alandau** [comment]
> Edit 1: 192.168.0.8 is my phone

This might be the clue! It happens when the phone screen is off. `arpspoof` uses the `ResolveIpNetEntry2()` function to resolve the victim IP into a MAC address, and the message is printed on failure. I just checked with my phone and indeed the arp table (as shown by `arp -a`) does NOT list an entry for my phone. However if I retry `arpspoof` with the phone screen being on, `arpspoof` works correctly and `arp -a` shows an entry for it.

If this doesn't help, you can add a print statement just before the `return false` here https://github.com/alandau/arpspoof/blob/master/arpspoof.cpp#L113. The value to print should be the return of the `ResolveIpNetEntry2(&row, &srcif)` call on the preceding line. Perhaps this will shed some light.

**Comment by 07c0ff3a590b** [comment]
@alandau Turns out when I uninstall nPcap (WinPcap), reboot the system, install it again, reboot and then run arpspoof It works just fine. The next time I reboot it prints out the exact same error. It's listing interfaces through **arpspoof --list** but It doesn't pick any IP addresses whatsoever.

You are also saying It could be due to the phone screen being turned off, I have tested this on the laptop and the phone as well and no, same error.

I did connect to my neighbors network with my phone, laptop and desktop PC and nope. Nothing.
What is interesting though is that programs like **Advanced IP Scanner**, **Angry IP Scanner** and the good old **ping** work fine. I can ping my devices without a problem. 1 Android and 2 Windows devices on the network. Yet after reboot I get the same old error like before: 

![cmd](https://user-images.githubusercontent.com/55628546/65392309-b4742980-dd73-11e9-97a4-ba6814f17e45.png)

**Comment by alandau** [comment]
Did you try adding the print I suggested?

The error message is due to a Windows function failing, it's not related at all to WinPcap, so the dance you're doing with reinstalling and rebooting is at best only marginally related. The `ResolveIpNetEntry2` function does an ARP lookup and it failing probably means the remote computer/phone didn't respond, but a print of the error message would confirm.

I just reran the test with my phone and 1 out of 5 tried with the screen off worked, while all 5 out of 5 worked with the screen on. It could be some timeout issue within `ResolveIpNetEntry2`, which would explain the screen on/off thing and why ping and the IP scanners work, but not why it fails with a laptop.

**Comment by 07c0ff3a590b** [comment]
I have fixed the issue, there was some sort of "collision" with a disabled device in device manager which was used for networking purposes. Uninstalling the unused device and rebooting the system made the arpspoof work as expected. Second day now and no issues.

The device was TP Link Wireless USB Adapter.

**Comment by alandau** [comment]
Glad you solved the issue, and thanks for reporting back!
